cask_args appdir: '/Applications'

tap "azure/draft"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jenkins-x/jx"
tap "gjbae1212/gossm"
tap 'isen-ng/dotnet-sdk-versions'
tap 'kudulab/dojo-osx'
tap 'versent/homebrew-taps'
tap 'vectordotdev/brew'
tap 'mike-engel/jwt-cli'
tap 'aquasecurity/trivy'
tap 'nats-io/nats-tools'

brew 'mas'

# compilers/env/sdk managers
cask 'anaconda'
brew 'nuget'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'fnm'
brew 'rbenv'
brew 'go'
brew 'ghc'
brew 'cocoapods'
brew 'erlang'
brew 'elixir'
brew 'mono-libgdiplus'
cask 'dotnet-sdk'
cask 'dotnet-sdk2-2-400'
brew 'dep'
brew 'rustup'

# important apps
cask 'caffeine'
cask 'flycut'
cask 'google-backup-and-sync'
cask 'google-chrome'
#cask 'parallels'
cask 'plistedit-pro'
cask 'sublime-text'

# password managers/security
cask '1password'
cask 'dropbox'
cask 'gpg-suite'
cask 'keybase'
brew 'blackbox'
brew 'cfssl'
brew 'openssl'
brew 'pwgen'
brew 'talisman'

# ides
cask 'jetbrains-toolbox'
cask 'visual-studio-code'
mas 'Xcode', id: 497799835

# dbs and infra
cask 'postgres', { appdir: '/Applications' }
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'SQLPro for Postgres', id: 976140091
brew 'postgresql@14'
cask 'dbvisualizer'
cask 'mongodb-compass-community'
brew 'circleci'
brew 'sqlite'
brew 'dive'
brew 'lima'
brew 'colima'
brew 'docker'
brew 'docker-compose'
brew 'dojo'
brew 'ansible'
brew 'awscli'
brew 'azure-cli'
brew 'draft'
cask 'google-cloud-sdk'
brew 'gossm'
brew 'jx'
brew 'k3d'
brew 'k9s'
brew 'kind'
brew 'kops'
brew 'kubernetes-cli'
brew 'helm'
cask 'minikube'
brew 'nats'
brew 'nats-server'
cask 'nosql-workbench'
brew 'packer'
cask 'powershell'
brew 'redis'
brew 's3cmd'
brew 'terraform'
brew 'terraform-docs'
brew 'terragrunt'
brew 'tfsec'
brew 'trivy'
cask 'vagrant'
cask 'virtualbox'

# misc apps
cask 'microsoft-office'
cask 'cyberduck'
cask 'discord'
cask 'owasp-zap'
cask 'react-native-debugger'
cask 'snipaste'
cask 'slack'
cask 'steam'
cask 'zoom'
mas 'Keynote', id: 409183694
mas 'Kindle', id: 405399194
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541

# dev
brew 'act'
brew 'adr-tools'
brew 'bash'
brew 'bash-completion'
brew 'bfg'
brew 'caddy'
brew 'certstrap'
brew 'cloc'
brew 'cntlm'
brew 'ctop'
# brew 'curl'
brew 'dbmate'
brew 'dos2unix'
brew 'flow'
brew 'gcc'
brew 'git'
brew 'gomplate'
brew 'graphviz'
brew 'jq'
brew 'jwt-cli'
brew 'inetutils'
cask 'insomnia'
brew 'ipcalc'
brew 'lnav'
brew 'magic-wormhole'
cask 'microsoft-teams'
brew 'mitmproxy'
brew 'ncdu'
brew 'opa'
brew 'pngcrush'
cask 'postman'
brew 'protobuf'
brew 'shellcheck'
brew 'sops'
brew 'swagger-codegen'
cask 'teamviewer'
brew 'tldr'
brew 'tmux'
brew 'unrar'
brew 'upx'
brew 'vite'
brew 'vector'
brew 'watch'
brew 'wget'
cask 'wireshark'
brew 'yarn'
brew 'zlib'
